# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchresult',
            old_name='search',
            new_name='job',
        ),
        migrations.AddField(
            model_name='searchresult',
            name='location',
            field=models.CharField(default='california', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='result',
            field=models.CharField(max_length=2000000),
        ),
    ]
